### ISSUE TITLE
Requires root privilege and writes into /root

### ISSUE THREAD

**Issue by nkadel** [MrMEEE/ansible-awx-depends#1]
It's not clear which of these scripts are still in use. But the scripts are written to only run as the root user. which is dangerous, and to drop symlinks into /usr/bin/python3.6, which conflicts with the EPEL version of Python 3..6.

This can be done reasonably gracefully as a non-root user using "mock" with epel-7-x86_64 configurations. I have samples of such setups over at https://gitnub.com/nkadel/samba4repo/, where I build up the dependencies and binaries for Samba 4.10.6. I'd be happy to submit a pull request for such a layout.

**Comment by nkadel** [comment]
I've been publishing updates to the "py2pack" tool for building .spec files, and have published a py2pack template just for rh-python36. See https://github.com/nkadel/py2packrepo and especially the rh-python36.spec file. py2pack is not perfect, and it doesn't catch all the Requires and bin files, so some tweaking can be needed. But it's a really useful starting place for generating matching spec files.

I've started using these, along with a customized "sclpy36-7-x86_64.cfg" file build from /etc/mock/epel-7-x86_64.cfg. The current working copy is at https://github.com/nkadel/nkadel-ansible-awx-depends/tree/nkadel-mock/buildrepo .

**Comment by MrMEEE** [comment]
Hi

These scripts are not in use anymore.. Everything is implemented in ansible..

I'm currently using first the built-in setup command to generate the specs and then spec2scl to create sol..

**Comment by MrMEEE** [comment]
Hi @nkadel 

I finally got around to moving on to the EL8 release of AWX-RPM.. 

Do you have any experience with the using py2pack and EL8/python??

Right now I'm facing an issue where packages should be prefixed with python36 instead of just python..

**Comment by nkadel** [comment]
Yeah, I've been publishing my up2dates to py2pack over at https://github.com/nkadel/py2packrepo/ . Step one is to not use the "scl" based  versions of Python. Step two is to add "epel-rpm-macros" as a BuildRequires, to get python3_pkgversion consistently set. Step three is to always use "python%{python3_pkgversion}" instead of "python3-" or "python36-" for dependencies.

**Comment by MrMEEE** [comment]
Have you made a py2pack template for RHEL8-EPEL-Python3

**Comment by nkadel** [comment]
Not a *distinct* one. I've updated the fedora.spec.in in https://github.com/nkadel/py2packrepo to be compatible with modern Fedora and the latest RHEL, both of which should no longer compile python2 packages by default. See https://github.com/nkadel/py2packrepo/blob/master/python-py2pack-srpm/fedora.spec.in

**Comment by nkadel** [comment]
And oh, since CentOS 7 and RHEL 7 now include built-in python 3.6, and RHEL 6 now can use Python 3.4 from EPEL, I'm no longer including sclo python hooks automatically. Do take a look at the matching mock configuration files I have there in the Makefile, to generate mock setups pointed to the local build yum repos.

**Comment by nkadel** [comment]
Project has gone dark. Closing old issues.
