### ISSUE TITLE
python module RPM names inconsistent with sclo standard

### ISSUE THREAD

**Issue by nkadel** [MrMEEE/ansible-awx-depends#3]
SCLO would normally name a python RPM such as "adal" something like "rh-python36-python-adal". This would avoid potential conflict with RHEL or EPEL python module names that lack the standard "python2-" or "python3-" prefixes, of which there are some left, and allow setting dependencies consistently for thee particular modules.

**Comment by nkadel** [comment]
Additionally, the .spec files would be named "python-[module].spec", rather than "[module]-scl.spec" I can understand keeping them segregated by the name of the .spec file, but it makes the SRPMs confusing to compare to upstream SRPMs.

**Comment by MrMEEE** [comment]
Right now I'm following the output from the setup rpm generator for naming, but you are correct..

Also, for now I don't wanna be using the same names as the standard, as the package versions in awx is sometimes older than the standard packages in RHEL/CentOS

**Comment by nkadel** [comment]
Using "a different name" by simply excluding the "python-" stanza from the package name is going to cause confusion about dependencies and conflicts, especially since some modules include an explicit "python-" in the name of the module itself. Examples include "python-memcached" and "python-dateutil".

I can understand the desire to segregate the packages, and their names, from the standard RHEL and CentOS packagelines. I'd suggest that, if RHEL is publishing an updated version of a python module, it's probably better integrated and tessted and you *should* use it in stead. If you must use distinct names, I'd encourage putting a prefix of "scl-" in front of the packagenames, or "pythonscl"-" instead of "python-", to segregate them more legibly than making the .spec file have a "-scl" in the name bu tnot actually put the name in the package.

I also recognize it would be a bunch of work to do, and you may have more critical tasks on your queue.

**Comment by MrMEEE** [comment]
Thanks for the input.. I think I will be moving the packages to something like "awxrpm-python-".. even though it will not be right now.. Alternatively I will create a completely new scl, but that means that I would have to maintain the base python36 packages as well.. (recompile RH packages, which I already do for Power)..

Also, I will be looking into RHEL8/CentOS8 support in the near future, the modules approach might give some ideas for this.

**Comment by MrMEEE** [comment]
Moving this to the common issuetracker
