### ISSUE TITLE
Dependency chains not resolved for python modules

### ISSUE THREAD

**Issue by nkadel** [MrMEEE/ansible-awx-depends#4]
The python modules have dependency chains, where one module must be built and installed before another module can be compiled,  These include Twisted and cryptography, that rely on the incremental module,  If these are built on a local system that is automatically having all the RPM's installed, that works. But on a clean system, or one using "mock" to avoid installing testing modules in a build environment permanently, they need to be built and installed in order.

Fortunately, "mock" allows deploying the modules only in a safe and rebuildable chroot environment, and can help straighten this out.

**Comment by MrMEEE** [comment]
Hi

I have implemented similar functionality in ansible, utilizing docker..  But I will look into mock, when I have the time

**Comment by nkadel** [comment]
If you've a setup that allows access to yum, but not to setup.py to use pip, I'd be very curious. mock does it by locking /etc/resolv.conf to an empty state, and "yum" is funneled through the docker environment in.... a fascinating setup of tweak that use the yum configuration specified for mock, itself. It's how I use mock to access a locally built up yum repo of already built RPMs, as laid out at https://github.com/nkadel/nkadel-ansible-awx-depends/tree/nkadel-mock/buildrepo .

**Comment by MrMEEE** [comment]
Basicly I'm not denying access to the internet in my initial builds on my home system. Here I just instruct setup.py to fetch all sourcecode (instead of wheels and other stuff), and then build that packages individually (automated process)..

Then, I commit the src.rpm's to copr, which actually builds the packages with mock (and no internet access)..

**Comment by nkadel** [comment]
I'm not sure how copr is building them, then. When I use mock, a number of them fail outright for requirements such as setuptools_scm and six and Twisted, which are built by these .spec files. It's why I've published a Makefile with dependencies for the distinct modules, both for BuildRequires and for Requires so that dependencies are built up to install dependencies. See https://github.com/nkadel/nkadel-ansible-awx-depends/blob/nkadel-mock/buildrepo/Makefile

**Comment by nkadel** [comment]
Test this with the Django module, which requires roughly 10 of the other modules already installed to successfully build without a network connection. Its dependences are definitely listed in the Makefile

**Comment by MrMEEE** [comment]
When I get the time I will look into this, but it seems like I implemented the same logic into ansible.. I've just not added the dependencies to the spec files

**Comment by nkadel** [comment]
Is that ansible playbook or setup published somewhere?

**Comment by nkadel** [comment]
Project has gone dark. Closing old issues.
