### ISSUE TITLE
Compiling as root pip installs unrequested, unpackaged dependency modules for some modules

### ISSUE THREAD

**Issue by nkadel** [MrMEEE/ansible-awx-depends#5]
Compiling the python modules with "mock" has revealed that some modules will install unrequested modules with setup.py. If performed as a root user, as the current setup requires, this can replace root owned python modules on the system without notice, especially RPM bundled modules.

This is precisely why root should never be permitted to compile RPMs, and it's a long known, built-in danger of running "setup.py" or "pip" as root. The "mock" tools do the compilation in a chroot cage for which /etc/resolv.conf is locked, and left empty, to reduce the risk of "pip" or other tools from reaching out to the Internet during compilation. I'd like to encourage you to shift your workflow to a mock based config.

**Comment by MrMEEE** [comment]
Thanks for all the info.. I have already taken care of the "unwanted" dependencies... the rpms are being compiled at copr without internet access, so pip won't be able to pull down anything..

**Comment by MrMEEE** [comment]
When I have the time I WILL look into the mock approach..

**Comment by nkadel** [comment]
Project has gone dark. Closing old issues.
